exhibit cache-machine bug
% py.test src/olympia/reviews/tests/test_views.py::TestReviewViewSetPost

src/olympia/reviews/tests/test_views.py:776: in test_post_logged_in
    assert response.status_code == 201, response.content
E   AssertionError: {"version":["Incorrect type. Expected pk value, received int."]}
E   assert 400 == 201
E    +  where 400 = <rest_framework.response.Response object at 0x7fbc75214bd0>.status_code

That's caused by rest_framework PrimaryKeyRelatedField evaluating the queryset, if you
place a breakpoint in rest_framework/relations.py in PrimaryKeyRelatedField.to_internal_value()
when it does the .get(pk=data) you'll see it.